### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by qtdyn** [natanbc/native-loader#1]
Due to Apple introducing their new M1 chips, running on ARM architecture, I was wondering if support for them would be added?

**Comment by Stonedestroyer** [comment]
I think we are being blocked by https://github.com/google/cpu_features/pull/204, one suggestion is to do a workaround to add support and hardcode it.

**Comment by qtdyn** [comment]
Thanks for the info, but since the project was archived not long after my issue, I decided to write my own loader [(here if you're interested)](https://github.com/stardust-enterprises/yanl).
